// Builds the distributable files and regenerates src/experiments/index.js.
//
//   dist/bn-lab-simulations.mjs      ES module, every experiment included
//   dist/bn-lab-simulations.js       browser global `BNLab`, readable
//   dist/bn-lab-simulations.min.js   browser global `BNLab`, minified
//   dist/bn-lab-simulations.css      default controls stylesheet
//
// Consumers with a bundler should import from src/ (see package.json
// "exports") so only the experiments they use are shipped.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const dir = path.join(root, 'src/experiments');

// ── Registry of experiments, in a stable alphabetical order ──
const ids = fs.readdirSync(dir)
  .filter(f => f.endsWith('.js') && f !== 'index.js')
  .map(f => f.slice(0, -3))
  .sort();
const ident = id => id.replace(/-(\w)/g, (_, c) => c.toUpperCase());
fs.writeFileSync(path.join(dir, 'index.js'),
  '/* Generated by scripts/build.mjs — do not edit by hand. */\n\n' +
  ids.map(id => `import ${ident(id)} from './${id}.js';`).join('\n') + '\n\n' +
  `export { ${ids.map(ident).join(', ')} };\n\n` +
  `export const experiments = [\n  ${ids.map(ident).join(',\n  ')}\n];\n\n` +
  'export default experiments;\n');

// Keep the version constant in sync with package.json.
const indexFile = path.join(root, 'src/index.js');
fs.writeFileSync(indexFile, fs.readFileSync(indexFile, 'utf8')
  .replace(/export const version = '[^']*';/, `export const version = '${pkg.version}';`));

const banner = `/*! BN Lab Simulations v${pkg.version} | MIT License | ${pkg.homepage} */`;
const common = { entryPoints: [path.join(root, 'src/bundle.js')], bundle: true, target: 'es2019', legalComments: 'inline', banner: { js: banner } };
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });

await esbuild.build({ ...common, format: 'esm', outfile: path.join(root, 'dist/bn-lab-simulations.mjs') });
await esbuild.build({ ...common, format: 'iife', globalName: 'BNLab', outfile: path.join(root, 'dist/bn-lab-simulations.js') });
await esbuild.build({ ...common, format: 'iife', globalName: 'BNLab', minify: true, legalComments: 'eof', outfile: path.join(root, 'dist/bn-lab-simulations.min.js') });
fs.copyFileSync(path.join(root, 'src/style.css'), path.join(root, 'dist/bn-lab-simulations.css'));

const kb = f => (fs.statSync(path.join(root, 'dist', f)).size / 1024).toFixed(1) + ' KB';
console.log(`${ids.length} experiments · bn-lab-simulations.min.js ${kb('bn-lab-simulations.min.js')} · bn-lab-simulations.mjs ${kb('bn-lab-simulations.mjs')}`);
